# Generated by Django 2.1.8 on 2019-07-15 15:17

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190715_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_image', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
