# Generated by Django 2.1.8 on 2019-05-15 12:00

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190515_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
    ]
