# Generated by Django 2.1.8 on 2019-07-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190715_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='image',
        ),
    ]
