# Generated by Django 2.1.8 on 2019-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190515_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
