# Generated by Django 2.1.8 on 2019-07-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
