# Generated by Django 2.1.8 on 2019-05-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190514_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='subtitle',
            field=models.CharField(default='', max_length=250),
        ),
    ]
