# Generated by Django 2.1.8 on 2019-08-25 06:33

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('blog', '0003_auto_20190721_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_thumbnail', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='thumbnail_preview',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_thumbnail_preview', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_thumbnail', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_preview',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_thumbnail_preview', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
