# Generated by Django 2.1.8 on 2019-05-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190515_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='slug', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(default='slug', max_length=100),
        ),
    ]
