# Generated by Django 2.1.8 on 2019-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190515_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_preview',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='thumbnail_preview',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
