# Generated by Django 2.1.8 on 2019-05-15 12:03

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190515_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail_preview',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='thumbnail_preview',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
    ]
